all:	basic header

dan:
	python -m unittest danWorks.TestSimpleFilter.test_basic

tuple:
	python -m unittest tupleTests.py

header:
	python -m unittest headerTests.py

basic:
	python -m unittest basicTests.py